"""Tests for the HTML report (report_html): valid HTML, content, escaping and crosswalk."""

from interaction_review.report_html import render_findings_html
from interaction_review.schemas import Dossier, Finding, Severity, Source, SourceKind


def _dossier() -> Dossier:
    return Dossier(
        system_name="Sistema X",
        domain="cribado",
        sources=[Source(id="d", kind=SourceKind.DOCUMENT, label="ficha", content="c")],
    )


def _finding(**kw) -> Finding:
    base = dict(id="f1", title="Score prerrellenado", guideline_ids=["HAX-G2"],
                locus="pantalla", evidence="el score aparece marcado", severity=Severity.HIGH)
    base.update(kw)
    return Finding(**base)


def test_is_self_contained_html_document():
    html = render_findings_html(_dossier(), [_finding()], "p3")
    assert html.startswith("<!doctype html>")
    assert html.rstrip().endswith("</html>")
    assert "<style>" in html  # embedded CSS, no external dependencies
    assert "http://" not in html and "https://" not in html  # no network resources


def test_contains_system_and_finding_content():
    html = render_findings_html(_dossier(), [_finding()], "p3")
    assert "Sistema X" in html
    assert "Score prerrellenado" in html
    assert "HAX-G2" in html
    assert "el score aparece marcado" in html


def test_escapes_html_in_dynamic_content():
    """Free text from the dossier/finding must not inject markup."""
    evil = _finding(title="<script>alert(1)</script>", evidence="a & b < c")
    html = render_findings_html(_dossier(), [evil], "p3")
    assert "<script>alert(1)</script>" not in html
    assert "&lt;script&gt;" in html
    assert "a &amp; b &lt; c" in html


def test_grounded_vs_generic_badge():
    grounded = render_findings_html(_dossier(), [_finding()], "p3")
    assert "Anchored" in grounded
    bare = render_findings_html(_dossier(), [_finding(guideline_ids=[], locus="", evidence="")], "b0")
    assert "Not anchored" in bare


def test_stats_counts():
    findings = [_finding(id="a"), _finding(id="b", severity=Severity.LOW), _finding(id="c", guideline_ids=[], locus="", evidence="")]
    html = render_findings_html(_dossier(), findings, "p3")
    assert ">3<" in html  # 3 findings
    # 2 of 3 grounded = 67%
    assert "67%" in html


def test_crosswalk_optional():
    with_cw = render_findings_html(_dossier(), [_finding()], "p3", include_crosswalk=True)
    without = render_findings_html(_dossier(), [_finding()], "p3", include_crosswalk=False)
    assert "Regulatory crosswalk" in with_cw
    assert "Regulatory crosswalk" not in without
    assert "not a legal opinion" in with_cw.lower()


def test_empty_findings_message():
    html = render_findings_html(_dossier(), [], "b0")
    assert "No findings" in html
    assert ">0<" in html  # 0 findings in the stats


def test_merged_count_shown():
    html = render_findings_html(_dossier(), [_finding(merged_count=4)], "p3")
    assert "Consolidates 4" in html


def test_meta_provenance_in_footer():
    # For a compliance file the report must carry date/model/version.
    html = render_findings_html(
        _dossier(), [_finding()], "p3",
        meta={"date": "2026-07-03", "tool_version": "0.0.1", "model": "claude-haiku-4-5"},
    )
    assert "2026-07-03" in html
    assert "0.0.1" in html
    assert "claude-haiku-4-5" in html


def test_no_meta_keeps_footer_clean():
    html = render_findings_html(_dossier(), [_finding()], "p3")
    assert "Generated by the human-AI interaction layer reviewer" in html


def test_crosswalk_includes_guideline_notes():
    # _finding() cites HAX-G2, which carries a curated map note.
    html = render_findings_html(_dossier(), [_finding()], "p3", include_crosswalk=True)
    assert "Why these map" in html
